name: Build Executables

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-release:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: windows-latest
            file: server.exe
            file-name: ts3-manager-win-x64-${{ github.event.release.tag_name }}.exe
          - os: ubuntu-latest
            file: server
            file-name: ts3-manager-linux-x64-${{ github.event.release.tag_name }}
          - os: macos-latest
            file: server
            file-name: ts3-manager-macos-x64-${{ github.event.release.tag_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: |
          npm install
          npm run build --if-present

      - name: Upload binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: packages/server/${{ matrix.file }}
          asset_name: ${{ matrix.file-name }}
          tag: ${{ github.ref }}
          overwrite: true
          
  publish-docker:
    name: Publish Docker images
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64,arm
        
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7,linux/arm/v6
          push: true
          tags: |
            ${{secrets.DOCKER_USER}}/ts3-manager:${{ github.event.release.tag_name }}
            ${{secrets.DOCKER_USER}}/ts3-manager:latest
          
          
          
