name: Build Executables

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-release:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: windows-latest
            build-script: build-win-exe
            file: win-exe.exe
            file-name: ts3-manager-win-x64-${{ github.event.release.tag_name }}.exe
          - os: ubuntu-latest
            build-script: build-linux-exe
            file: linux-exe
            file-name: ts3-manager-linux-x64-${{ github.event.release.tag_name }}
          - os: macos-latest
            build-script: build-macos-exe
            file: macos-exe
            file-name: ts3-manager-macos-x64-${{ github.event.release.tag_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: |
          npm --prefix ./frontend install ./frontend
          npm --prefix ./frontend run build
          npm --prefix ./backend install ./backend
          npm --prefix ./backend run ${{ matrix.build-script }} --if-present

      - name: Upload binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.file }}
          asset_name: ${{ matrix.file-name }}
          tag: ${{ github.ref }}
          overwrite: true
